export const colors = {
  "#FD3832": ["apple", "plum", "date", "berry", "wolfberry", "peach", "tomato"],
  "#C5F321": [
    "lime",
    "pear",
    "watermelon",
    "kiwi",
    "melon",
    "honeydew",
    "olive",
  ],
  "#F9EEA0": ["lychee", "guava", "melon", "banana", "quince"],
  "#FCAB1D": [
    "orange",
    "mango",
    "apricot",
    "persimmon",
    "kumquat",
    "papaya",
    "loquat",
    "pineapple",
    "longan",
    "jackfruit",
  ],
  "#5D0AEA": ["grape", "fig", "prune"],
};
